### ISSUE TITLE
work tracker

### ISSUE THREAD

**Issue by linhub15** [linhub15/idify#3]
- [x] web forms to fill in with data
- [x] button to trigger camera
- [x] capture image and send to server
- [x] server process image into structured data
- [x] server respond with JSON
- [x] JS handles JSON response in callback from POST request to fill the form

### Presentation
- [x] talking points
- [x] slide show
